// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: platform/fabric/core/fabricx/committer/v2/protoqueryservice/query.proto

package protoqueryservice

import (
	context "context"
	protoblocktx "github.com/hyperledger/fabric-x-endorser/platform/fabricx/core/fabricx/committer/v2/protoblocktx"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryService_GetRows_FullMethodName     = "/protoqueryservice_rc_0_2.QueryService/GetRows"
	QueryService_BeginView_FullMethodName   = "/protoqueryservice_rc_0_2.QueryService/BeginView"
	QueryService_EndView_FullMethodName     = "/protoqueryservice_rc_0_2.QueryService/EndView"
	QueryService_GetPolicies_FullMethodName = "/protoqueryservice_rc_0_2.QueryService/GetPolicies"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryServiceClient interface {
	GetRows(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Rows, error)
	BeginView(ctx context.Context, in *ViewParameters, opts ...grpc.CallOption) (*View, error)
	EndView(ctx context.Context, in *View, opts ...grpc.CallOption) (*View, error)
	GetPolicies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*protoblocktx.Policies, error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) GetRows(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Rows, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rows)
	err := c.cc.Invoke(ctx, QueryService_GetRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) BeginView(ctx context.Context, in *ViewParameters, opts ...grpc.CallOption) (*View, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(View)
	err := c.cc.Invoke(ctx, QueryService_BeginView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) EndView(ctx context.Context, in *View, opts ...grpc.CallOption) (*View, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(View)
	err := c.cc.Invoke(ctx, QueryService_EndView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetPolicies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*protoblocktx.Policies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(protoblocktx.Policies)
	err := c.cc.Invoke(ctx, QueryService_GetPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility.
type QueryServiceServer interface {
	GetRows(context.Context, *Query) (*Rows, error)
	BeginView(context.Context, *ViewParameters) (*View, error)
	EndView(context.Context, *View) (*View, error)
	GetPolicies(context.Context, *Empty) (*protoblocktx.Policies, error)
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServiceServer struct{}

func (UnimplementedQueryServiceServer) GetRows(context.Context, *Query) (*Rows, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRows not implemented")
}
func (UnimplementedQueryServiceServer) BeginView(context.Context, *ViewParameters) (*View, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginView not implemented")
}
func (UnimplementedQueryServiceServer) EndView(context.Context, *View) (*View, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndView not implemented")
}
func (UnimplementedQueryServiceServer) GetPolicies(context.Context, *Empty) (*protoblocktx.Policies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicies not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}
func (UnimplementedQueryServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_GetRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetRows(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_BeginView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).BeginView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_BeginView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).BeginView(ctx, req.(*ViewParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_EndView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(View)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).EndView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_EndView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).EndView(ctx, req.(*View))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetPolicies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoqueryservice_rc_0_2.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRows",
			Handler:    _QueryService_GetRows_Handler,
		},
		{
			MethodName: "BeginView",
			Handler:    _QueryService_BeginView_Handler,
		},
		{
			MethodName: "EndView",
			Handler:    _QueryService_EndView_Handler,
		},
		{
			MethodName: "GetPolicies",
			Handler:    _QueryService_GetPolicies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/fabric/core/fabricx/committer/v2/protoqueryservice/query.proto",
}
